improved restore

diff --git a/bin/backup b/bin/backup
--- a/bin/backup
+++ b/bin/backup
@@ -83,38 +83,37 @@ cleanup() {
 trap cleanup SIGINT
 
 # Check if the mariadb container is running
-if docker ps | grep -q "$CONTAINER"; then
-    # do backup of mariadb domjudge database using mariadb-dump command withing docker container
-    # notes:
-    # - environment variables MYSQL_ROOT_PASSWORD and MYSQL_DATABASE set in docker-compose.yml
-    # - we use the max packet size of 1G, but it could crash docker container by to much memory usage.
-    #   With  'get_maximum_blob_size_in_bytes_in_mariadb' we could determine a more safe limit.
-    #   However for simplicity we stick to the max. Only in case of problems we could decrease it.
-    #   Note: backups are run at night, so this problem possibly would not occur.
-    set -o pipefail
-    
-    docker exec -t "$CONTAINER" /bin/bash -c '/usr/bin/mariadb-dump --single-transaction --quick --routines --events --triggers --hex-blob --max-allowed-packet='"$MAX_PACKET_SIZE"' --user root -p$MYSQL_ROOT_PASSWORD $MYSQL_DATABASE' | gzip -$GZIP_COMPRESSION > "${dumpfile}.temp"
-    #echo docker exec -t "$CONTAINER" /bin/bash -c '/usr/bin/mariadb-dump --single-transaction --quick --routines --events --triggers --hex-blob --max-allowed-packet='"$MAX_PACKET_SIZE"' --user root -p$MYSQL_ROOT_PASSWORD $MYSQL_DATABASE' \| gzip -$GZIP_COMPRESSION \> "$dumpfile"
-    exit_status=$?
-    
-    if [[ $exit_status -ne 0 ]]; then
-        error "dumping mariadb database failed" 
-        rm "${dumpfile}.temp"
-        exit $exit_status
-    else
-        # verify for 'Dump completed' in dumpfile
-        if zcat "${dumpfile}.temp" | tail -n 1  | grep -q 'Dump completed'; then
-            mv "${dumpfile}.temp" "${dumpfile}"
-            info "Database backup successful. Dump saved to: $dumpfile"
-        else
-            error "The database dump was not completed successfully."
-            error  "Dumping mariadb database finished without error, but dumpfile does not confirm its completed with 'Dump completed'" 
-            rm "${dumpfile}.temp"
-            exit 1
-        fi
-    fi
-
-else
-    error "The 'mariadb' docker container is not running." >&2
+if ! docker ps | grep -q "$CONTAINER"; then
+    error "The 'mariadb' docker container is not running."
     exit 1
 fi
+
+# do backup of mariadb domjudge database using mariadb-dump command within docker container
+# notes:
+# - environment variables MYSQL_ROOT_PASSWORD and MYSQL_DATABASE set in docker-compose.yml
+# - we use the max packet size of 1G, but it could crash docker container by to much memory usage.
+#   With  'get_maximum_blob_size_in_bytes_in_mariadb' we could determine a more safe limit.
+#   However for simplicity we stick to the max. Only in case of problems we could decrease it.
+#   Note: backups are run at night, so this problem possibly would not occur.
+set -o pipefail
+docker exec -t "$CONTAINER" /bin/bash -c '/usr/bin/mariadb-dump --single-transaction --quick --routines --events --triggers --hex-blob --max-allowed-packet='"$MAX_PACKET_SIZE"' --user root -p$MYSQL_ROOT_PASSWORD $MYSQL_DATABASE' | gzip -$GZIP_COMPRESSION > "${dumpfile}.temp"
+exit_status=$?
+if [[ $exit_status -ne 0 ]]; then
+    error "dumping mariadb database failed" 
+    rm "${dumpfile}.temp"
+    exit $exit_status
+else
+    # verify for 'Dump completed' in dumpfile
+    if zcat "${dumpfile}.temp" | tail -n 1  | grep -q 'Dump completed'; then
+        mv "${dumpfile}.temp" "${dumpfile}"
+        info "Database backup successful. Dump saved to: $dumpfile"
+    else
+        error "The database dump was not completed successfully."
+        error  "Dumping mariadb database finished without error, but dumpfile does not confirm its completed with 'Dump completed'" 
+        rm "${dumpfile}.temp"
+        exit 1
+    fi
+fi
+
+
+
diff --git a/bin/restore-backup b/bin/restore-backup
--- a/bin/restore-backup
+++ b/bin/restore-backup
@@ -1,21 +1,57 @@
 #!/bin/bash
 
-#TODO: after checking  tail contains completed  compress the backup dump with gzip!!
-#TODO: exclude big tables => verify if they really cam be skippped
-#        docker exec -t mariadb /bin/bash -c '/usr/bin/mariadb-dump --ignore-table-data domjudge.judging_run_output --ignore-table-data domjudge.testcase_content --skip-quick --user root -p$MYSQL_ROOT_PASSWORD $MYSQL_DATABASE' >$dumpfile
 
-
+# Config
+MAX_PACKET_SIZE="1G"
+CONTAINER="mariadb"
 
 # Define usage information
 USAGE="Usage: $(basename "$0") [-h|--help] FILEPATH
 
-Restore the domjudge MariaDB database from a dumpfile 
+DESCRIPTION
+   Restore the domjudge MariaDB database from a dumpfile 
 
-Options:
+OPTIONS
   -h, --help    Display this help message and exit.
 
-Arguments:
+ARGUMENTS
   FILEPATH      The path where the database dump file will is located.
+
+EXAMPLE
+  First bring your containers down. 
+     
+     $ docker compose down
+
+  Then start only the mariadb database container
+
+     $ docker compose up -d mariadb
+
+  Restore the database from a dumpfile     
+  
+     $ bin/restore-backup data/backups/mariadb.sql.gz
+     INFO: Restoring from the dumpfile 'data/backups/mariadb.sql.gz'
+     INFO: dumping mariadb database succesful
+
+  Delete the old passwords files, 
+  and let new ones generated on start of the domserver container 
+
+     $ sudo rm  data/passwords/*   
+
+  Start all containers 
+
+     $ docker compose up -d
+      ✔ Network caddy_reverseproxy  Created
+      ✔ Container mariadb           Running
+      ✔ Container domserver         Started
+      ✔ Container judgehost-1       Started
+      ✔ Container judgehost-0       Started
+
+   Now you should be able to login as 'admin' user using the password
+   in data/passwords/admin.pw 
+
+   Note that if you remembered the admin password of the backup, 
+   then you could skip resetting the admin password. 
+
 "
 
 info() {
@@ -52,25 +88,35 @@ if [[ -z "$dumpfile" ]]; then
 fi      
 
 if [[ -f "$dumpfile" ]]; then
-    echo "Restoring from the dumpfile '$dumpfile'" >&2
+    info "Restoring from the dumpfile '$dumpfile'" 
 else
-    echo "The dumpfile '$dumpfile' does not exist." >&2
+    error "The dumpfile '$dumpfile' does not exist." 
     exit 1
 fi
 
-# check mariadb service is running
-if ! docker ps | grep -q mariadb; then
-    echo "ERROR: no mariadb docker process running" >&2
+
+
+# Check if the mariadb container is running
+if ! docker ps | grep -q "$CONTAINER"; then
+    error "The 'mariadb' docker container is not running." 
     exit 1
 fi
 
+# restore database from dumpfile using mariadb command within the docker container
 # environment variables MYSQL_ROOT_PASSWORD and MYSQL_DATABASE set in docker-compose.yml
-#docker exec -t mariadb /bin/bash -c '/usr/bin/mariadb-dump --user root --max-allowed-packet='"$MAX_PACKET_SIZE"'  -p$MYSQL_ROOT_PASSWORD $MYSQL_DATABASE' < $dumpfile
-cat sdf
+set -o pipefail
+gunzip -c "$dumpfile" | \
+docker exec -i "$CONTAINER" /bin/bash -c \
+'/usr/bin/mariadb --max-allowed-packet='"$MAX_PACKET_SIZE"'  --user root  -p$MYSQL_ROOT_PASSWORD $MYSQL_DATABASE' 
+
+# gunzip -c "$dumpfile" | \
+# docker exec -i "$CONTAINER" /bin/bash -c \
+# "/usr/bin/mariadb --max-allowed-packet=$MAX_PACKET_SIZE --user root -p\$MYSQL_ROOT_PASSWORD \$MYSQL_DATABASE"
+
 exit_status=$?
 if [[ $exit_status -ne 0 ]]; then
-    echo "ERROR: restoring mariadb database failed" >&2
+    error "restoring mariadb database failed" 
     exit $exit_status
 else
-    echo "INFO: dumping mariadb database succesful" >&2
+    info "dumping mariadb database succesful" 
 fi
