added verification of checksum when it exist before doing restore

diff --git a/bin/restore-backup b/bin/restore-backup
--- a/bin/restore-backup
+++ b/bin/restore-backup
@@ -54,10 +54,10 @@ EXAMPLE
 "
 
 info() {
-   echo "INFO: $@" 1>&2
+   echo "INFO: $*" 1>&2
 }
 error() {
-   echo "ERROR: $@" 1>&2
+   echo "ERROR: $*" 1>&2
 }
 
 # Parse command line options
@@ -84,7 +84,13 @@ if [[ -z "$dumpfile" ]]; then
 fi
 
 if [[ -f "$dumpfile" ]]; then
-   info "Restoring from the dumpfile '$dumpfile'"
+   if [[ "$dumpfile" == *.sql.gz ]]; then
+      info "Restoring from the dumpfile '$dumpfile'"
+   else
+      error "The dumpfile '$dumpfile' does NOT end with '.sql.gz'."
+      exit 1
+   fi
+
 else
    error "The dumpfile '$dumpfile' does not exist."
    exit 1
@@ -96,16 +102,29 @@ if ! docker ps | grep -q "$CONTAINER"; then
    exit 1
 fi
 
+# verify the integrity of the dumpfile using sha256 checksum
+
+# Check for the existence of the hash file next to the backup
+if [[ -f "$dumpfile.sha256" ]]; then
+   info "Verifying integrity of dumpfile '$(basename $dumpfile)' using checksum in '$(basename $dumpfile.sha256)'"
+   scriptdir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
+   FILE_HASH=$("$scriptdir"/backup-checksum "$dumpfile")
+   VERIFY_HASH=$(cat "$dumpfile.sha256")
+   if [[ "$FILE_HASH" != "$VERIFY_HASH" ]]; then
+      error "The integrity check of the dumpfile '$dumpfile' failed."
+      error "The checksum does not match the expected value in '$dumpfile.sha256'."
+      exit 1
+   else
+      info "The integrity check of the dumpfile '$dumpfile' succeeded."
+   fi
+fi
+
 # restore database from dumpfile using mariadb command within the docker container
 # environment variables MYSQL_ROOT_PASSWORD and MYSQL_DATABASE set in docker-compose.yml
 set -o pipefail
 gunzip -c "$dumpfile" |
    docker exec -i "$CONTAINER" /bin/bash -c \
       '/usr/bin/mariadb --max-allowed-packet='"$MAX_PACKET_SIZE"'  --user root  -p$MYSQL_ROOT_PASSWORD $MYSQL_DATABASE'
-
-# gunzip -c "$dumpfile" | \
-# docker exec -i "$CONTAINER" /bin/bash -c \
-# "/usr/bin/mariadb --max-allowed-packet=$MAX_PACKET_SIZE --user root -p\$MYSQL_ROOT_PASSWORD \$MYSQL_DATABASE"
 
 exit_status=$?
 if [[ $exit_status -ne 0 ]]; then
