improved backup , can backup database running in docker container or remote server host

diff --git a/backup/bin/mariadb-rolling-backup b/backup/bin/mariadb-rolling-backup
--- a/backup/bin/mariadb-rolling-backup
+++ b/backup/bin/mariadb-rolling-backup
@@ -5,14 +5,13 @@ SCRIPTDIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
 SCRIPTNAME=$(basename "$0")
 
 # --- Default Configuration ---
-NAME="mariadb"
 NUM_TO_KEEP=20
 # When running in the container, the script is at /usr/bin/rolling-backup
 # so then the default backup dir is /data/backups/ which is mounted at /data/
 # when running from outside the container, this script is in backup/bin/
 # the backups dir is at data/backups/ in the git repo of DOMjudgeDockerCompose,
 # so the default backup dir is:
-BACKUP_DIR="$SCRIPTDIR/../../data/backups/"
+BACKUP_DIR="$PWD/backups/"
 # When running inside the container, the script is at /app/rolling-backup
 # and the backups dir is bind mounted at /backups. However when we want
 # to change the backup dir, we would need to change the bind mount in the
@@ -27,29 +26,67 @@ NAME
     $SCRIPTNAME - Rolling backup of a DOMjudge database
 
 SYNOPSIS 
-    $SCRIPTNAME [OPTIONS] 
+    $SCRIPTNAME [OPTIONS] DATABASE
 
 OPTIONS 
-  -d, --dir DIR      Set backup directory (default: $SCRIPTDIR/../data/backups/)
+  --user USER_NAME, -u USER_NAME
+                     The MariaDB user name to use when connecting to the server.
+                     (default: current system user's name)
+  --password PASSWORD, -p PASSWORD
+                     The password to use when connecting to the server. 
+  -H HOSTNAME, --host HOSTNAME 
+                     The hostname of the MariaDB server.
+                     If neither a container name nor a host name is provided, 
+                     then localhost is used as host name. 
+  -C CONTAINER, --container CONTAINER
+                     The name of the Docker container running MariaDB 
+                     If neither a container name nor a host name is provided, 
+                     then localhost is used as host name.                         
+  -d, --dir DIR      Set backup directory (default: ./backups/)
   -k, --keep NUM     Number of unique backups to keep (default: 20)
-  -n  --no-check     No checksums. Equivalent backups not removed.
+  -c, --checksum     Create checksums (default: true if -r option used, false otherwise)
+                     The checksums are stored in a file next to the backup file
+                     with the same name but with a .sha256 extension.
+
+  -e, --exclude-tables-in-checksum TABLES
+                     Comma separated list of tables to exclude from checksum calculation
+                     (default: none)
+  -r, --remove-eq-prev      
+                     Remove previous backup if checksum equivalent with new backup.
+                     This option implies the -c option.
   -h, --help         Show this help message and exit
 
+
+
 DESCRIPTION
-  This script creates rolling backups of a DOMjudge database. It uses an
-  external 'backup' script for the dump and a 'backup-checksum' script
-  for a special checksum. The backups are stored in a specified
-  directory.
+  This script creates rolling backups of a mariadb database. It uses an
+  external 'mariadb-backup' script for creating a good hashable backup,
+  and a 'mariadb-backup-checksum' script for a configurable special 
+  checksum. The backups are stored in the specified directory.
   
-  To save space, the script only keeps a specified number of unique
-  backups. Uniqueness is determined by comparing the special checksums of
-  the new and most recent backups. The checksum script is designed
-  specifically for DOMjudge; it ignores tables with non-essential,
-  frequently changing timestamp and logging data to identify truly
-  meaningful changes in the database.
+  By default the script creates a new backup every time it is run,
+  and keeps NUM_TO_KEEP backups. If more then NUM_TO_KEEP backups
+  exist, the oldest are deleted.  
+
+  Using the option -c, the script creates checksums for each backup.
+  This can be helpful to verify the integrity of the backups.
+  The mariadb-restore-backup script use these checksums to verify
+  the integrity of a backup before restoring it.
   
-  When a new backup is created, its checksum is compared to the most
-  recent one:
+  To save more space, the script can optimize the backup storage
+  by removing the previous backup if it is equivalent to the new
+  backup. Then only when the database has really changed a new backup
+  is kept. This is done using the -r option. This option implies 
+  the -c option.
+  
+  Because some tables in the database may contain frequently changing
+  timestamp or logging data which is not essential for detecting changes
+  in the main data, the checksum calculation can be configured to ignore
+  such tables. This is done by providing a comma separated list of
+  tables to exclude from the checksum calculation using the -e option.
+
+  When using the -r option and a new backup is created, its checksum 
+  is compared to the most recent one:
   
   - If checksums are different, the new backup is added to the history,
     and the oldest is discarded to maintain the specified number of
@@ -60,22 +97,19 @@ DESCRIPTION
     kept, even if the main data hasn't changed. This is important
     because configuration data in the tables ignored by the checksum may
     have been updated.
-  
-  Use the -n option to disable checksum comparison and keep every single
-  backup.
 
 EXAMPLES
 
   In below examples we assume the script is called daily from cron.
 
-    $SCRIPTNAME -d /tmp/backups -k 10
+    $SCRIPTNAME -r -d /tmp/backups -k 10 
       Daily makes a new backup in /tmp/backups. It does keep 10 unique backups,
       where equivalent backups are discarded. So we could have backups older
       then 10 days.
 
-    $SCRIPTNAME -n
+    $SCRIPTNAME 
       Make a daily backup. By default the command keeps 20 backups, one per
-      day until 20 days back. Where without -n option in case of equivalent
+      day until 20 days back. Where with -r option in case of equivalent
       backups we could  have backups older then 20 days.
 
 EOF
@@ -91,9 +125,33 @@ error() {
 
 # --- Parse arguments ---
 
-CHECK="true"
-while [[ $# -gt 0 ]]; do
+USERNAME=""
+PASSWORD=""
+HOST=""
+CONTAINER=""
+REMOVE_EQUIVALENT_PREV="false"
+CREATE_CHECKSUM="false"
+EXCLUDE_TABLES=""
+while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do
     case "$1" in
+    -u | --user)
+        # disable checksum comparison, meaning no equivalent backup is discarded
+        USERNAME="$2"
+        shift 2
+        ;;
+    -p | --password)
+        # disable checksum comparison, meaning no equivalent backup is discarded
+        PASSWORD="$2"
+        shift 2
+        ;;
+    -H | --host)
+        HOST="$2"
+        shift 2
+        ;;
+    -C | --container)
+        CONTAINER="$2"
+        shift 2
+        ;;
     -d | --dir)
         BACKUP_DIR="$2"
         shift 2
@@ -102,10 +160,20 @@ while [[ $# -gt 0 ]]; do
         NUM_TO_KEEP="$2"
         shift 2
         ;;
-    -n | --no-check)
-        # disable checksum comparison, meaning no equivalent backup is discarded
-        CHECK="false"
+    -c | --checksum)
+        # enable creation of checksum
+        CREATE_CHECKSUM="true"
         shift 1
+        ;;
+    -r | --remove-eq-prev)
+        # disable checksum comparison, meaning no equivalent backup is discarded
+        REMOVE_EQUIVALENT_PREV="true"
+        shift 1
+        ;;
+    -e | --exclude-tables-in-checksum)
+        # disable checksum comparison, meaning no equivalent backup is discarded
+        EXCLUDE_TABLES="$2"
+        shift 2
         ;;
     -h | --help)
         usage
@@ -118,6 +186,18 @@ while [[ $# -gt 0 ]]; do
         ;;
     esac
 done
+
+if [[ "$REMOVE_EQUIVALENT_PREV" == "true" ]]; then
+    CREATE_CHECKSUM="true"
+fi
+
+DATABASE="$1"
+if [[ -z "$DATABASE" ]]; then
+    error "No database name provided."
+    usage >&2
+    exit 1
+fi
+NAME="$DATABASE"
 
 # --- Cleanup old backups ---
 
@@ -158,17 +238,14 @@ cleanup_old_backups() {
 # checksum comparison to discard equivalent backups.
 discard_equivalent_previous_backup() {
 
-    # Store the hash of the new temporary dump file
-    info "Generating hash of backup in $(basename "$DUMPFILE.sha256")"
-    "$SCRIPTDIR"/backup-checksum "$DUMPFILE" >"$DUMPFILE.sha256"
-
     # Compare with last backup using hashes of the new and last backups
     # and if identical discard the new backup
 
     # Check for the existence of the hash file next to the last backup
+    # note: for the new backup we always create the hash file in this script before calling this function
     if [[ ! -f "$LAST_BACKUP.sha256" ]]; then
         info "Previous backup's hash file not found. Generating it now in  $(basename "$LAST_BACKUP.sha256")"
-        "$SCRIPTDIR"/backup-checksum "$LAST_BACKUP" >"$LAST_BACKUP.sha256"
+        "$SCRIPTDIR"/mariadb-backup-checksum --exclude-tables "$EXCLUDE_TABLES" "$LAST_BACKUP" >"$LAST_BACKUP.sha256"
     fi
 
     # Read the stored hash of the last backup
@@ -215,7 +292,7 @@ info "Backup started in $BACKUP_DIR"
 #       which itself outputs info and error messages.
 #       The backup script creates the backup folder
 #       if it does not exist.
-"$SCRIPTDIR"/backup "$TEMP_DUMPFILE"
+"$SCRIPTDIR"/mariadb-backup --user "$USERNAME" --password "$PASSWORD" --host "$HOST" --container "$CONTAINER" "$DATABASE" "$TEMP_DUMPFILE"
 
 # # test lines to simulate a backup
 # # - changed content
@@ -231,16 +308,18 @@ fi
 
 # If we reach here, it means the backup was successful.
 mv "$TEMP_DUMPFILE" "$DUMPFILE"
+info "Backup saved as $(basename "$DUMPFILE")."
 
-if [[ -f "$LAST_BACKUP" ]]; then
-    # we have a previous backup
-    # Only if CHECK true then we discard an equivalent previous backup
-    if [[ "$CHECK" == "true" ]]; then
-        discard_equivalent_previous_backup
-    fi
-    # cleanup old backups if we have more then NUM_TO_KEEP backups
-    cleanup_old_backups
-else
-    # we do not have previous backup(s)
-    info "First backup saved as $(basename "$DUMPFILE")."
+# create checksum of new backup if requested
+if [[ "$CREATE_CHECKSUM" == "true" ]]; then
+    info "Generating hash of backup in $(basename "$DUMPFILE.sha256")"
+    "$SCRIPTDIR"/mariadb-backup-checksum --exclude-tables "$EXCLUDE_TABLES" "$DUMPFILE" >"$DUMPFILE.sha256"
 fi
+
+# remove previous backup if equivalent to new backup and if requested
+if [[ -f "$LAST_BACKUP" && "$REMOVE_EQUIVALENT_PREV" == "true" ]]; then
+    discard_equivalent_previous_backup
+fi
+
+# cleanup old backups if we have more then NUM_TO_KEEP backups
+cleanup_old_backups
